pipeline:
  build:
    image: frebib/alpine-cmake:3.6
    environment:
      - NO_SETCAP=true
      - PACKAGES=libcap-dev
    commands:
      # Run the default entrypoint
      - /usr/local/bin/entrypoint true
      # Build with make
      - make clean all
      # Build with cmake
      - SRC="$(pwd)"
      - DIR="$(mktemp -dt cmake-build.XXXXXX)"
      - cd "$DIR"
      - cmake "$SRC"
      - make

  test:
    image: alpine:3.6
    privileged: true
    environment:
      - RAWSOCK_NOBIND=true
    commands:
      - apk --no-cache --quiet add coreutils libcap make valgrind
      - make --warn-undefined-variables install PREFIX=/usr
      # Ensure there are no relative paths in range so netd links to /usr/bin
      - cd /
      - ldconfig /usr/lib
      - ldd /usr/bin/netd
      # ret 124 is a timeout therefore it did not crash
      - timeout -s SIGINT 10
          valgrind
            --leak-check=full
            --show-reachable=yes
            --track-origins=yes
            netd >/dev/null 
          || test $? -eq 124

matrix:
  CC:
    - gcc
    - clang
