pipeline:
  build:
    image: frebib/alpine-cmake:3.6
    environment:
      - NO_SETCAP=true
      - PACKAGES=libcap-dev
    commands:
      - mkdir -p build
      - cd build
      - cmake ..
      - make

  test:
    image: alpine:3.6
    commands:
      - test -f build/libnet.so
      - test -f build/netd -a -x build/netd
