pipeline:
  build:
    image: frebib/alpine-cmake:3.6
    environment:
      - NO_SETCAP=true
      - PACKAGES=libcap-dev
    commands:
      # Run the default entrypoint
      - /usr/local/bin/entrypoint true
      - mkdir -p build
      - cd build
      - cmake ..
      - make

  test:
    image: alpine:3.6
    privileged: true
    environment:
      - RAWSOCK_NOBIND=true
    commands:
      - apk --no-cache --quiet add libcap coreutils
      - test -f build/libnet.so
      - test -f build/netd -a -x build/netd
      - ldd build/netd
      # ret 124 is a timeout therefore it did not crash
      - timeout 10 build/netd || test $? -eq 124
