pipeline:
  build:
    image: frebib/alpine-cmake:3.6
    environment:
      - NO_SETCAP=true
      - PACKAGES=libcap-dev
    commands:
      # Run the default entrypoint
      - /usr/local/bin/entrypoint true
      - CC=$CC make

  test:
    image: alpine:3.6
    privileged: true
    environment:
      - RAWSOCK_NOBIND=true
    commands:
      - apk --no-cache --quiet add coreutils libcap make
      - make --warn-undefined-variables install PREFIX=/usr
      - ldconfig /usr/lib
      - ldd /usr/bin/netd
      # ret 124 is a timeout therefore it did not crash
      - timeout 10 netd >/dev/null || test $? -eq 124

matrix:
  CC:
    - gcc
    - clang
